version: '2.3'

services:
  web:
    # php -v => PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
    # nginx -v => nginx/1.14.0 (Ubuntu)
    image: passwork/nginx-php7
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/site.conf:/etc/nginx/sites-enabled/site.conf
      - ./conf/php:/server/conf/php
      - ./conf/postfix:/server/conf/postfix
      - ./conf/ssl:/server/conf/ssl
      - ./log/nginx:/server/log/nginx
      - ./log/php:/server/log/php
      - ./log/syslog:/server/log/syslog
      - ./site/:/server/site/
      - ./permissions:/usr/bin/permissions
    command: bash -c "permissions && /server/run"

  mongo:
    # mongo > db.version() => 3.0.15
    image: passwork/mongo
    volumes:
    - ./conf/mongo:/server/conf
    - ./log/mongo:/server/log
    - ./data/mongo:/server/data
