version: '2.3'

services:
  web:
    image: passwork/nginx-php7
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/site.conf:/etc/nginx/sites-enabled/site.conf
      - ./conf/php:/server/conf/php
      - ./conf/postfix:/server/conf/postfix
      - ./conf/ssl:/server/conf/ssl
      - ./log/mongo:/server/log/mongo
      - ./log/nginx:/server/log/nginx
      - ./log/php:/server/log/php
      - ./log/syslog:/server/log/syslog
      - ./site/:/server/site/
      - ./permissions:/usr/bin/permissions
    command: bash -c "permissions && /server/run"

  mongo:
    image: passwork/mongo
    volumes:
    - ./conf/mongo:/server/conf
    - ./log/mongo:/server/log
    - ./data/mongo:/server/data
